FROM nginx:1.11
RUN echo "Asia/Shanghai" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
RUN mkdir /etc/cert
COPY . /var/www/html
COPY ./nginx/nginx.production.conf /etc/nginx/conf.d/default.conf
RUN chown -R www-data:www-data /var/www
RUN chmod -R 777 /var/www/html/storage