FROM nginx:1.11
RUN echo "Asia/Shanghai" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
RUN mkdir /etc/letsencrypt
COPY ./nginx.staging.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
